- name: Install Required System Packages
  apt:
    name: "{{ prerequirements}}"
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release  }} stable"
    state: present

- name: Install Docker
  apt:
    name: "{{docker}}"
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: "{{item}}"
  loop:
    - docker 
    - docker-compose 
