variables:
  KUBE_CONTEXT: root/k8s-connection:k8s-connection

stages:
  - build
  - push
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --tag="$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME" .

push:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME"

deploy-dev:
  stage: deploy
  environment:
    name: dev
  tags:
    - dev
  script:
    - docker compose pull
    - docker compose down
    - docker compose up -d

deploy-prod:
  stage: deploy
  when: manual
  environment:
    name: prod
  tags:
    - prod
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context $KUBE_CONTEXT

    - kubectl apply -f $CI_PROJECT_DIR/k8s-files/sql-deployment.yml
    - kubectl get deployment -n py-app -o wide

    - kubectl apply -f $CI_PROJECT_DIR/k8s-files/app-deployment.yml
    - kubectl get deployment -n py-app -o wide
