- name: Install Required System Packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker
