- name: Copy Docker-Compose File
  copy: 
    src: "files"
    dest: "/home/{{ admin_user }}/wordpress/mariadb"

- name: Set Permission for Docker Daemon
  file:
    path: /var/run/docker.sock
    mode: '0770'

- name: Docker Compose Up
  shell:
    chdir: "/home/{{ admin_user }}/wordpress/mariadb/files/"
    cmd: docker compose -f main.yml up -d
