---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: py-app
  name: py-app
  labels:
    app: py-app             
spec:
  accessModes:
    - ReadWriteOnce            
  resources:
    requests:
      storage: 1Gi            
  storageClassName: py-app
