---
apiVersion: v1
kind: Service
metadata:
  name: exposer
  namespace: py-app
  labels:
    app: python
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: python
    tier: frontend            
  type: NodePort              

---
apiVersion: v1
kind: Service
metadata:
  name: internal-connection
  namespace: py-app
  labels:
    app: python            
spec:
  ports:
    - port: 5432              
  selector:
    app: python            
    tier: sql               
  clusterIP: None             
